version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.1
      nodejs: 20
    commands:
      - gem install bundler -v 2.5.10
      - bundle install --deployment
  build:
    commands:
      - SECRET_KEY_BASE=`./bin/rails secret` RAILS_ENV=production bundle exec rails assets:precompile
  post_build:
    commands:
      - tar czf radio-backend.tgz --exclude-vcs --exclude=spec --exclude=tmp --exclude=log *
artifacts:
  files:
    - 'radio-backend.tgz'
