version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.1
    commands:
      - gem install bundler -v 2.3.26
      - bundle install
  build:
    commands:
      - bundle exec rake build
  post_build:
    commands:
      - bundle exec rake deploy
