version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.1
      nodejs: 20
    commands:
      - gem install bundler -v 2.3.26
      - bundle install --deployment
      - yarn install
      - RAILS_ENV=production bundle exec rails assets:precompile
      - tar czf radio-backend.tgz --exclude-vcs --exclude=spec --exclude=tmp --exclude=log *
artifacts:
  files:
    - 'radio-backend.tgz'
