version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.4
    commands:
      - gem install bundler -v 2.5.10
      - bundle config set deployment true
      - bundle config set path 'vendor/bundle'
      - bundle install
  post_build:
    commands:
      - tar czf radio-backend.tgz --exclude-vcs --exclude=spec --exclude=tmp --exclude=log *
artifacts:
  files:
    - 'radio-backend.tgz'
