require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/choosers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Chooser. As you add validations to Chooser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Chooser.create! valid_attributes
      get choosers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      chooser = Chooser.create! valid_attributes
      get chooser_url(chooser)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_chooser_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      chooser = Chooser.create! valid_attributes
      get edit_chooser_url(chooser)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Chooser" do
        expect {
          post choosers_url, params: { chooser: valid_attributes }
        }.to change(Chooser, :count).by(1)
      end

      it "redirects to the created chooser" do
        post choosers_url, params: { chooser: valid_attributes }
        expect(response).to redirect_to(chooser_url(Chooser.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Chooser" do
        expect {
          post choosers_url, params: { chooser: invalid_attributes }
        }.to change(Chooser, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post choosers_url, params: { chooser: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested chooser" do
        chooser = Chooser.create! valid_attributes
        patch chooser_url(chooser), params: { chooser: new_attributes }
        chooser.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the chooser" do
        chooser = Chooser.create! valid_attributes
        patch chooser_url(chooser), params: { chooser: new_attributes }
        chooser.reload
        expect(response).to redirect_to(chooser_url(chooser))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        chooser = Chooser.create! valid_attributes
        patch chooser_url(chooser), params: { chooser: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested chooser" do
      chooser = Chooser.create! valid_attributes
      expect {
        delete chooser_url(chooser)
      }.to change(Chooser, :count).by(-1)
    end

    it "redirects to the choosers list" do
      chooser = Chooser.create! valid_attributes
      delete chooser_url(chooser)
      expect(response).to redirect_to(choosers_url)
    end
  end
end
