require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/streams", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Stream. As you add validations to Stream, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:stream)
  }

  describe "GET /index" do
    it "renders a successful response", :as_logged_in_user do
      allow_any_instance_of(ApplicationController).to receive(:current_user) do
        @_spec_current_user ||= create(:user)
      end

      create(:stream)
      get streams_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    before(:each) do
      allow_any_instance_of(ApplicationController).to receive(:current_user).and_return(@logged_in_user)
    end

    it "renders fields private to the owner of the stream as owner", :as_logged_in_user do
      stream = create(:stream, user: @logged_in_user)
      get stream_url(stream)
      json = JSON.parse(response.body)
      expect(json).to have_key("default_rating")
    end

    it "does not render fields private to the owner of the stream as non-owner", :as_logged_in_user do
      stream = create(:stream)
      get stream_url(stream)
      json = JSON.parse(response.body)
      expect(json).not_to have_key("default_rating")
    end

    it "does not expose sensitive mastodon_access_token", :as_logged_in_user do
      stream = create(:stream, user: @logged_in_user, mastodon_access_token: "secret")
      get stream_url(stream)
      json = JSON.parse(response.body)
      expect(json).not_to have_key("mastodon_access_token")
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Stream", :as_logged_in_user do
        expect {
          post streams_url, params: { stream: valid_attributes }
        }.to change(Stream, :count).by(1)
      end
    end
  end

  describe "PATCH /update" do
    context "without mastodon access token" do
      it "doesn't clear out the token", :as_logged_in_user do
        stream = create(:stream, user: @logged_in_user)
        patch stream_url(stream), params: { stream: { name: "New stream name", mastodon_access_token: ""} }
        stream.reload
        expect(stream.mastodon_access_token).to be_present
      end
    end

    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: "NewName"
        }
      }

      it "updates the requested stream", :as_logged_in_user do
        stream = create(:stream, user: @logged_in_user)
        patch stream_url(stream), params: { stream: new_attributes }
        stream.reload
        expect(response).to be_successful
      end
    end
  end

  describe "POST /random_songs" do
    context "as owner", :as_logged_in_user do
      before do
        @stream = create(:stream, user: @logged_in_user, default_rating: 42)
        @songs = create_list(:song, 10)
      end

      it "adds random songs to the stream" do
        expect {
          post random_songs_stream_path(@stream), params: { count: 5 }
        }.to change { @stream.choosers.count }.by(5)

        expect(response).to have_http_status(:ok)
        json = response.parsed_body
        expect(json["added"]).to eq(5)
        expect(json["total"]).to eq(5)
      end

      it "uses the stream default_rating for new choosers" do
        post random_songs_stream_path(@stream), params: { count: 3 }
        expect(@stream.choosers.pluck(:rating)).to all(eq(42))
      end

      it "does not add songs already in the stream" do
        create(:chooser, stream: @stream, song: @songs.first)

        post random_songs_stream_path(@stream), params: { count: 100 }

        json = response.parsed_body
        expect(json["added"]).to eq(9)
        expect(json["total"]).to eq(10)
      end

      it "caps count at 500" do
        post random_songs_stream_path(@stream), params: { count: 1000 }

        json = response.parsed_body
        # Only 10 songs exist, so at most 10 can be added
        expect(json["added"]).to eq(10)
      end

      it "treats count less than 1 as 1" do
        post random_songs_stream_path(@stream), params: { count: 0 }

        json = response.parsed_body
        expect(json["added"]).to eq(1)
      end
    end

    context "as non-owner", :as_logged_in_user do
      it "returns unauthorized" do
        other_user = create(:user)
        stream = create(:stream, user: other_user)

        post random_songs_stream_path(stream), params: { count: 5 }
        expect(response).to have_http_status(:unauthorized)
      end
    end

    context "unauthenticated" do
      it "returns unauthorized" do
        stream = create(:stream)

        post random_songs_stream_path(stream), params: { count: 5 }
        expect(response).to have_http_status(:unauthorized)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested stream", :as_logged_in_user do
      stream = create(:stream, user: @logged_in_user)
      expect {
        delete stream_url(stream)
      }.to change(Stream, :count).by(-1)
    end
  end
end

