require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/streams", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Stream. As you add validations to Stream, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Stream.create! valid_attributes
      get streams_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      stream = Stream.create! valid_attributes
      get stream_url(stream)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_stream_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      stream = Stream.create! valid_attributes
      get edit_stream_url(stream)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Stream" do
        expect {
          post streams_url, params: { stream: valid_attributes }
        }.to change(Stream, :count).by(1)
      end

      it "redirects to the created stream" do
        post streams_url, params: { stream: valid_attributes }
        expect(response).to redirect_to(stream_url(Stream.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Stream" do
        expect {
          post streams_url, params: { stream: invalid_attributes }
        }.to change(Stream, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post streams_url, params: { stream: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "PATCH /update" do
    context "without mastodon access token" do
      it "doesn't clear out the token", :as_logged_in_user do
        stream = create(:stream, user: @logged_in_user)
        patch stream_url(stream), params: { stream: { name: "New stream name", mastodon_access_token: ""} }
        stream.reload
        expect(stream.mastodon_access_token).to be_present
      end
    end

    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested stream" do
        stream = Stream.create! valid_attributes
        patch stream_url(stream), params: { stream: new_attributes }
        stream.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the stream" do
        stream = Stream.create! valid_attributes
        patch stream_url(stream), params: { stream: new_attributes }
        stream.reload
        expect(response).to redirect_to(stream_url(stream))
      end
    end

    context "with invalid parameters" do

      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        stream = Stream.create! valid_attributes
        patch stream_url(stream), params: { stream: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested stream" do
      stream = Stream.create! valid_attributes
      expect {
        delete stream_url(stream)
      }.to change(Stream, :count).by(-1)
    end

    it "redirects to the streams list" do
      stream = Stream.create! valid_attributes
      delete stream_url(stream)
      expect(response).to redirect_to(streams_url)
    end
  end
end
